name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Vous pouvez ajuster la version Node.js selon vos besoins

      - name: Install dependencies and build your site
        run: |
          npm install  # Installez les dépendances de votre projet
          npm run build  # Exécutez la commande de build spécifique à Astro

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          artifact_dir: 'dist'
